apiVersion: v1
kind: ReplicationController
metadata:
  name: mobile-server
  namespace: mobile
  labels:
    apiserver: "true"
    app: "api"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
        app: "api"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: mobile-server
        ports:
        - containerPort: 3101   
        image: feedhenry/mobile-apiserver:latest
        imagePullPolicy: Always
        args:
        - "--etcd-servers=http://localhost:2379"
        - "--secure-port=3101"
        - "--authentication-skip-lookup"
        #- "--authentication-kubeconfig=/mnt/apiserver-config/kubeconfig"
        #- "--authorization-kubeconfig=/mnt/apiserver-config/kubeconfig"
        #- "--client-ca-file=/mnt/apiserver-config/client-ca.crt"
        - "--tls-cert-file=/mnt/apiserver-config/serving.crt"
        - "--tls-private-key-file=/mnt/apiserver-config/serving.key"
        - "--v=5"
        volumeMounts:        
        - name: config-dir
          mountPath: /mnt/apiserver-config        
      - name: etcd
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379      
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always        
      volumes:
      - name: etcd-data-dir
        emptyDir: {}
      - name: config-dir
        hostPath:
          path: /mnt/mobile-apiserver/config
       